# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京喜牧场

on:
  workflow_dispatch:
  schedule:
    - cron: '31 0-23/2 * * *'
  repository_dispatch:
    types: jxmc
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
   
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js 15.x
       uses: actions/setup-node@v1
       with:
           node-version: 15.x 
     - name: npm install
       run: |
          npm install
     - name: '运行 【京喜牧场】'
       run: |
          node jd_jxmc.js
       env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PUSH_PLUS_TOKEN: ${{ github.event.client_payload.PUSH_PLUS_TOKEN || secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ github.event.client_payload.PUSH_PLUS_USER || secrets.PUSH_PLUS_USER }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          QQ_SKEY: ${{ secrets.QQ_SKEY }}
          QQ_MODE: ${{ secrets.QQ_MODE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          QYWX_AM: ${{ secrets.QYWX_AM }}
          DREAM_FACTORY_SHARE_CODES: ${{ secrets.DREAM_FACTORY_SHARE_CODES }}
